### ISSUE TITLE
能不能支持socket.io的协议

### ISSUE THREAD

**Issue by xiongxt** [vanishs/umdwebsocket#1]
能不能支持socket.io的协议

**Comment by vanishs** [comment]
umdwebsocket只是提供简单的websocket封装，实现自动重连功能。
socket.io是封装了XMLHttpRequest 与WebSocket协议，并且实现on,emit的业务
所以你说实现socket.io协议意思应该是希望增加on,emit的业务，如果这么做了，就成为socket.io了，所以没必要实现这些功能
所我建议您有这样的需求的话还是用socket.io比较好

**Comment by vanishs** [comment]
或者你有什么想法可以提出来，我们可以探讨一下，我先关闭问题了。
